### ISSUE TITLE
Remote control with MQTT 

### ISSUE THREAD

**Issue by codegrau** [MiczFlor/RPi-Jukebox-RFID#581]
Hi there, thank you @MiczFlor and all contributors for this wonderful project. 

Since mqtt is very common for smart home and home automation stuff I was wondering: wouldn't it be cool for phonieboxes to connect to a mqtt broker for other devices to know, which tune is playing and control phoniebox remotely?

- Publish "now playing" to a selected mqtt topic
- Subscribe to a mqtt topic for remote control 

This way you could easily integrate phoniebox to openHAB or HomeAssistant or even use cheap ESP8266 to control or visualize phoniebox contents.

Looking forward to your thoughts.

**Comment by andreasbrett** [comment]
Awesome idea! Would love to use this as well with my openHAB setup.

**Comment by MiczFlor** [comment]
@codegrau @andreasbrett 
It's a great idea. I have no smart home, it's nice here, but not very smart ;) so I can't help with this idea. Makes sense though and I will be hovering over the pull requests - possibly you can create a small task group.

**Comment by andreasbrett** [comment]
I'll see if I can contribute to this feature. I need to dig into the phoniebox infrastructure first and see how and where to insert the mqtt stuff.

@codegrau any ideas on what exact features we would need to control/monitor via mqtt?

**Comment by andreasbrett** [comment]
@codegrau 
I think we can close this issue as it is implemented now.

**Comment by codegrau** [comment]
Sorry for my late response, but what you've achieved @andreasbrett is incredible! This is exactly what I meant! Thank you for this one!

**Comment by andreasbrett** [comment]
@codegrau thanks, it was easier than I thought. Let me know if there's something else that could be done with regards to MQTT.

**Comment by whenthelight** [comment]
Hey  @ all i had massive problems with Openhab and Mosquito to get and read States (Commands are without Errors and i have it run till google Home can control my Box :-) , thats so awesome), so test step by step and figured some errors (dont know its only me on rasbian buster?) :
1st: its not phoniebox/attributes/attributeName ist phoniebox/attribute/attributeName
2nd: with sample Conf for service in systemd the working Directory must be WorkingDirectory=/home/pi/RPi-Jukebox-RFID/scripts
not
WorkingDirectory=/home/pi/RPi-Jukebox-RFID
without the directory scripts you wont get attribute Values

Hope this help someone

Thanks to dev for this awesome script and Idea of Mqtt

**Comment by andreasbrett** [comment]
> 1st: its not phoniebox/attributes/attributeName ist phoniebox/attribute/attributeName

Fixed the typo in the wiki, thanks for pointing that out!

> 2nd: with sample Conf for service in systemd the working Directory must be WorkingDirectory=/home/pi/RPi-Jukebox-RFID/scripts
> not
> WorkingDirectory=/home/pi/RPi-Jukebox-RFID

Okay, I think I found the bug with that configuration. Typically my scripts are independent from the working directory as I use the script path. Thanks to your hint I found 3 attributes where I did NOT do so. maxvolume, idletime and volstep. Did you have issues with other attributes as well? Those 3 bugs will be fixed once @MiczFlor merges the pull request () into master. It contains some new features and I also added the fixes a minute ago.

**Comment by whenthelight** [comment]
> > 1st: its not phoniebox/attributes/attributeName ist phoniebox/attribute/attributeName
> 
> Fixed the typo in the wiki, thanks for pointing that out!
> 
> > 2nd: with sample Conf for service in systemd the working Directory must be WorkingDirectory=/home/pi/RPi-Jukebox-RFID/scripts
> > not
> > WorkingDirectory=/home/pi/RPi-Jukebox-RFID
> 
> Okay, I think I found the bug with that configuration. Typically my scripts are independent from the working directory as I use the script path. Thanks to your hint I found 3 attributes where I did NOT do so. maxvolume, idletime and volstep. Did you have issues with other attributes as well? Those 3 bugs will be fixed once @MiczFlor merges the pull request (#593) into master. It contains some new features and I also added the fixes a minute ago.

Hey, so fast :-) i couldn't drink my Pale and have to sit down for testing .
The Problem with the "scripts" path is wenn i start the service the "get/all" doesnt get Values in al Attributes. Not only these 3 but when it has merged i test some Attributes. actually this error appears only in the "get" and "attribute" topics , the cmd have no error and delivers without error. Also in the Syslog i see "get/all" empty Value . When start directly with python3 "script" no error and all topics become their Values

thx

**Comment by andreasbrett** [comment]
> PS: the new Function for Folderplay(which is incredible when i get this work as Switch and then in Google Home :-)) need some Parameters , are these the directory Path to Musicalbums ? like : /RPi-Jukebox-RFID/shared/audiofolders/Album1 or only Album1 ?

You simply pass the folder name (Album1). BTW: I primarily use the Basic UI to control openHAB and therefore would implement that with a String element that is linked to the MQTT topic "phoniebox/cmd/playfolder" and make a dropdown in the sitemap with pre-set folder names. Something like that:

	Selection item=phoniebox_playfolder mappings=["Album1"="Tool - Fear Inocolum", "Album2"="Slipknot - We are not your kind"]

Not sure how you would handle that with your Google Home though.

> Update: Change your Commit et voila , thumbsup all works like charm.

Great!

**Comment by KingKahn123** [comment]
Hi, I still have an issue with the MQTT function. I have connected the Phoniebox to my MQTT server of my IPSymcon system, but only 4 entries are created:

<img width="1298" alt="image" src="https://user-images.githubusercontent.com/26251558/66270228-29a22d00-e851-11e9-93d6-31ef6ea32d86.png">

The phoniebox/get/all attribute gets updated every 10 seconds when a music file is playing. However no data is written to this attribute. In the log files I can see that the payload for this attribute is NULL. 

Any idea why no information is forwarded to this attribute?

Thx for your help...

Kai

**Comment by andreasbrett** [comment]
@kingkahn123
You misunderstood the documentation. Attributes are sent to /attribute/$attributeName (so e.g. /attribute/volume or /attribute/elapsed).

/get/$attributeName only triggers phoniebox to publish that attribute to /attribute/$attributeName. That's only used if you want to receive the updates quicker or at a specific time rather than waiting for the next interval. What you will have to do though is set your smart home tool to monitor each attribute separately (via e.g. /attribute/volume).

**Comment by andreasbrett** [comment]
Oh and I see that you're using the Spotify edition. Haven't tested that yet as I'm not using it. Let me know if it works like I described above.

**Comment by KingKahn123** [comment]
I have created now one additional attribute manually:

<img width="1407" alt="image" src="https://user-images.githubusercontent.com/26251558/66270863-71788280-e858-11e9-815b-d90a3f6dad31.png">

The details look like this:

<img width="433" alt="image" src="https://user-images.githubusercontent.com/26251558/66270852-468e2e80-e858-11e9-8129-0932f9cee6ea.png">

However no updates are received for this attribute.

**Comment by KingKahn123** [comment]
In addition, as far as I understand the MQTT function from the Phoniebox is that all attributes are refreshed at a predefined interval, correct? That means during playback of any music file, the attributes are sent to the server every 10 seconds (depending on the config file). This would be recognized by my SmartHome system and the attributes would be created automatically. But only the four are created. So I assume that no data is transferred to my SmartHome system.

**Comment by whenthelight** [comment]
Hey, in Mqtt you have to subscribe to an Topic to receive an Attribute. You have to make an Status or SUB in your Software with phoniebox/attribute/Volume an no Value.

It seems that you set up an public with that Topic above and an Value

**Comment by KingKahn123** [comment]
But this is how my other attributes, where I receive some data from the Phoniebox, are defined.

<img width="430" alt="image" src="https://user-images.githubusercontent.com/26251558/66271174-49d6e980-e85b-11e9-9930-edd9b6b28eb6.png">

---------

Received information on startup:

<img width="1319" alt="image" src="https://user-images.githubusercontent.com/26251558/66271268-5576e000-e85c-11e9-90a7-7e3204165ed5.png">




This is how my MQTT server receives the publish get/all from the Phoniebox. The payload is empty. Should it not include some data?

   <img width="950" alt="image" src="https://user-images.githubusercontent.com/26251558/66271164-2dd34800-e85b-11e9-8e77-9883a594c979.png">

**Comment by whenthelight** [comment]
Sure ;-) because you use publish to publish plusSpotify to the Topic phoniebox/edition
You need an Function in your Ip_symcon that catchs the Values from the Topics not send some.
Like https://github.com/thomasf68/IPS_MQTT. 
You received this in your mqtt server because you published that  with your Action.

**Comment by andreasbrett** [comment]
> Should it not include some data?

No. Please read again the documentation and my description above. The get topic NEVER is filled with payload because the topic itself will trigger an action and does not need a payload as all the necessary information is already in the subtopic (attributename). The reason why your tool detects this topic is because the periodic publishing of attributes is triggered by phoniebox sending /get/all to itself. Just ignore that.

The reason you're not receiving any attributes has to do with you being on the Spotify edition. I will have to check how the management of the player (which I guess is different to the classic edition) works for the Spotify edition.

**Comment by andreasbrett** [comment]
@whenthelight He is not publishing anything. His tool just subscribed to all possible topics and phoniebox indeed is sending 4 parameters at the beginning (independent of the player attributes).

Reason why he does not receive any attributes is because that function seems to crash due to some difference between the classic and Spotify edition.

@miczflor
Are there major differences on how I can retrieve player data in the Spotify edition? As you see in my code I mostly use queries to mpd as well as the payout controls.sh script.

**Comment by KingKahn123** [comment]
> Sure ;-) because you use publish to publish plusSpotify to the Topic phoniebox/edition
> You need an Function in your Ip_symcon that catchs the Values from the Topics not send some.
> Like https://github.com/thomasf68/IPS_MQTT.
> You received this in your mqtt server because you published that with your Action.

This mqtt module was now integrated in IPSymcon 5.1/5.2. No need to have this module any longer ;-) When I create this attribute initially the value field is empty... After reboot of the Phoniebox the value is filled in by the MQTT publish:

<img width="659" alt="image" src="https://user-images.githubusercontent.com/26251558/66271453-69bbdc80-e85e-11e9-902d-f82fb9c44aa4.png">

**Comment by KingKahn123** [comment]
> @whenthelight He is not publishing anything. His tool just subscribed to all possible topics and phoniebox indeed is sending 4 parameters at the beginning (independent of the player attributes).
> 
> Reason why he does not receive any attributes is because that function seems to crash due to some difference between the classic and Spotify edition.

I think so as well as I now checked the log file of my IPSymcon MQTT server and I do not see anything else than the 4 parameters. The get/all is occurring every 10 seconds. But I now understood that it is ok, if it is empty ;-)

Thanks for looking into it

**Comment by whenthelight** [comment]
> @whenthelight He is not publishing anything. His tool just subscribed to all possible topics and phoniebox indeed is sending 4 parameters at the beginning (independent of the player attributes).
 **Hey im blind :-) didnt see that he is RX the Publish , sorry for missing this. I read the manual of the IPsymcon :-)** 
> Reason why he does not receive any attributes is because that function seems to crash due to some difference between the classic and Spotify edition.
> 
> @MiczFlor
> Are there major differences on how I can retrieve player data in the Spotify edition? As you see in my code I mostly use queries to mpd as well as the payout controls.sh script.


What is the output of journalctl -u phoniebox-mqtt-client.service there you see whats going on

**Comment by andreasbrett** [comment]
@kingkahn123
Could you please try the latest version of the mqtt daemon? It's not yet merged but includes some major changes that might already get rid of the errors. 

You can get it here:
https://github.com/andreasbrett/RPi-Jukebox-RFID/blob/mqtt-dev/scripts/daemon_mqtt_client.py

**Comment by KingKahn123** [comment]
> What is the output of journalctl -u phoniebox-mqtt-client.service there you see whats going on

<img width="1092" alt="image" src="https://user-images.githubusercontent.com/26251558/66271684-58280400-e861-11e9-9526-68ef89d4862d.png">

**Comment by andreasbrett** [comment]
You won't see the errors there as the function that causes the issue is called from a thread and not showing error messages on stdout/stderr.

Please try the latest dev version (see above) and check journalctl again. If I'm correct it should give more output and also attributes should pop up. If not... I will have to dig deeper.

**Comment by whenthelight** [comment]
Latest Dev gives a lot of Informations :-)
![image](https://user-images.githubusercontent.com/56171532/66271797-ac7fb380-e862-11e9-804c-23fa404772d2.png)

**Comment by whenthelight** [comment]
Spotify Edition use mopidy, customized Mpd 

https://docs.mopidy.com/en/latest/api/core/#mopidy.core.mopidy.core.PlaylistsController

**Comment by KingKahn123** [comment]
Using the new script results in only two more attributes:

<img width="274" alt="image" src="https://user-images.githubusercontent.com/26251558/66272370-45b1c880-e869-11e9-8f27-55ee94a0061d.png">

journalctl now only shows this:

<img width="632" alt="image" src="https://user-images.githubusercontent.com/26251558/66272420-c7a1f180-e869-11e9-92e2-a8e23a082d52.png">

**Comment by whenthelight** [comment]
All Music related Attributes are in the Spotify Edition others then normal, because mopidy act different then normal MPD.Thats why the Script cannot geht the Values for the Attributes. Thats why you get only the System Default Values

**Comment by andreasbrett** [comment]
@whenthelight
But how does phoniebox web app work then? It uses the same ways of accessing player status.

@kingkahn123 
Could you please add `fetchData()` at the bottom of the script right after `client.loop_start()`? This will allow us to see the error in journalctl.

**Comment by KingKahn123** [comment]
> @KingKahn123
> Could you please add `fetchData()` at the bottom of the script right after `client.loop_start()`? This will allow us to see the error in ` journalctl -u phoniebox-mqtt-client.service`


I have added it and this is the only output:

<img width="1164" alt="image" src="https://user-images.githubusercontent.com/26251558/66273861-51f15200-e878-11e9-9cfd-2fb00bd7ef9e.png">

**Comment by andreasbrett** [comment]
That's weird. I honestly don't know what to do right now. Are you able to see and control your box in the web app? Additionally, could you run the following command:

`nc - w 1 localhost 6600`

Then enter `status` and press enter. This should output some lines of attributes of your mpd/mopidy server. Then enter `close` and then press enter to close that tool.

**Comment by KingKahn123** [comment]
Yes, I can control the box via the web app...

> nc -w 1 localhost 6600 -->

<img width="534" alt="image" src="https://user-images.githubusercontent.com/26251558/66275565-12336600-e88a-11e9-9575-ae12e1b88925.png">

status gives following "result":

<img width="394" alt="image" src="https://user-images.githubusercontent.com/26251558/66275588-60e10000-e88a-11e9-9a0a-9ac9b6763c5e.png">

**Comment by andreasbrett** [comment]
No, enter status while still in the mpd console (that you opened with nc)

**Comment by KingKahn123** [comment]
It is not opening anything:

<img width="534" alt="image" src="https://user-images.githubusercontent.com/26251558/66275724-d6010500-e88b-11e9-9030-d91b643173af.png">

**Comment by andreasbrett** [comment]
My bad. Use that command: `nc localhost 6600`

**Comment by KingKahn123** [comment]
Ah ;-)

<img width="500" alt="image" src="https://user-images.githubusercontent.com/26251558/66275778-47d94e80-e88c-11e9-9f06-fb747d2d3a92.png">

**Comment by andreasbrett** [comment]
Okay, getting closer. Please save the following code to a file and name it test.py

	import subprocess
	
	cmd = ['nc', '-w', '1', 'localhost', '6600']
	input = 'status\ncurrentsong\nclose'.encode('utf-8')
	status = subprocess.run(cmd, stdout=subprocess.PIPE, input=input).stdout.decode('utf-8')
	print("result =", status)

Then run that with `python3 test.py`

**Comment by KingKahn123** [comment]
Done:

<img width="482" alt="image" src="https://user-images.githubusercontent.com/26251558/66275985-79ebb000-e88e-11e9-899f-4838996861c4.png">

**Comment by andreasbrett** [comment]
Alright, that's a good thing. 

Now please add the following lines to test.py and run it again. 

	regex = re.search('\nstate: (.*)\n', status).group(1).lower()
	print("regex =", regex)

**Comment by KingKahn123** [comment]
Where should I add it? Right at the end of the script after: print("result =", status) ?

**Comment by andreasbrett** [comment]
Yes, right there.

**Comment by KingKahn123** [comment]
Ok then I get following error message:

<img width="514" alt="image" src="https://user-images.githubusercontent.com/26251558/66276220-3181c180-e891-11e9-8878-96006eaf0cc7.png">

**Comment by andreasbrett** [comment]
Sorry change the first line of the script to

`import subprocess, re`

**Comment by andreasbrett** [comment]
(sorry for all the hassle. I'm on my smartphone right now and can't properly help)

**Comment by KingKahn123** [comment]
no worries... Thx for the help:

<img width="463" alt="image" src="https://user-images.githubusercontent.com/26251558/66276347-5aef1d00-e892-11e9-9ca5-de6388108a71.png">

**Comment by andreasbrett** [comment]
Okay, that all looks very good. Could you try running the mqtt script?

First stop the service with `sudo systemctl stop phoniebox-mqtt-client`

Then run the script manually with
`python3 daemon_mqtt_client.py`

**Comment by KingKahn123** [comment]
<img width="685" alt="image" src="https://user-images.githubusercontent.com/26251558/66276559-b7533c00-e894-11e9-937d-6d63a7f5f80d.png">

**Comment by andreasbrett** [comment]
Okay, this looks like the subscription to the /get/# topic did not work. Which mqtt server are you using? Could you try and send to /get/volume (any payload) from your smart home software? The daemon script needs to run while you're doing it. It should output that it received something.

**Comment by KingKahn123** [comment]
Ok that worked:

<img width="710" alt="image" src="https://user-images.githubusercontent.com/26251558/66276852-ecf92480-e896-11e9-8a50-afb80ae62b6b.png">

And my MQTT Server (IPSymcon) received the publish and saved it in the attribute:

<img width="1082" alt="image" src="https://user-images.githubusercontent.com/26251558/66276859-1023d400-e897-11e9-8697-03d2c749fbd7.png">

**Comment by andreasbrett** [comment]
Alright, I think I fixed it. Please download the script once again from latest dev (see link above).

**Comment by KingKahn123** [comment]
Perfect! It is working now ;-)

<img width="425" alt="image" src="https://user-images.githubusercontent.com/26251558/66277033-0602d500-e899-11e9-9e76-29628e04daf3.png">

**Comment by andreasbrett** [comment]
Awesome! Thanks for the patience and enjoy it. Let me know if there's something missing that you need/want.

**Comment by KingKahn123** [comment]
Are you kidding me?! Thanks for your patience and your help!

**Comment by MiczFlor** [comment]
I committed the last pull requests to master:
#600

**Comment by MiczFlor** [comment]
And thanks for the lively discussion and great input!

**Comment by whenthelight** [comment]
> > PS: the new Function for Folderplay(which is incredible when i get this work as Switch and then in Google Home :-)) need some Parameters , are these the directory Path to Musicalbums ? like : /RPi-Jukebox-RFID/shared/audiofolders/Album1 or only Album1 ?
> 
> You simply pass the folder name (Album1). BTW: I primarily use the Basic UI to control openHAB and therefore would implement that with a String element that is linked to the MQTT topic "phoniebox/cmd/playfolder" and make a dropdown in the sitemap with pre-set folder names. Something like that:
> 
> ```
> Selection item=phoniebox_playfolder mappings=["Album1"="Tool - Fear Inocolum", "Album2"="Slipknot - We are not your kind"]
> ```
> 
> So if I select the Slipknot album from that dropdown the value "Album2" would be sent to the `playfolder` command. Not sure how you would handle that with your Google Home though.
> 

Hey andreasbrett, If i select only 1 Album , i can handle this as Switch with 1 Value (Album1).
Items create as Switch et voila my Son is happy ;-) . Volume are configured as Dimmer  and Lightning. The Reaction Time is awesome fast. Sleeptimer also as Switch with Value in my Case 60 for 60min. Play and Pause also works good as Switch.

**Comment by georgbachmann** [comment]
Hey there... I love the idea of controlling my sons phoniebox with mqtt (f.e. to make it work as an alarm-clock). THANK YOU very much for your effort!!!

Maybe I was skimming over this issue here too fast... but is there a readme on how to activate the mqtt support? Like where to I configure my broker?

**Comment by georgbachmann** [comment]
Thank you guys a lot for this addon! I can't wait to realize a wake-up-alarm for my kids with it!
I can run it and it also works if I run it manually like so: `python3 RPi-Jukebox-RFID/scripts/daemon_mqtt_client.py`.
But when I follow the instructions on the wiki page and then run `sudo systemctl status phoniebox-mqtt-client` at the end, I always get error messages:

```pi@phoniebox:~ $ sudo systemctl status phoniebox-mqtt-client
● phoniebox-mqtt-client.service - Phoniebox MQTT Client Service
   Loaded: loaded (/etc/systemd/system/phoniebox-mqtt-client.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Sun 2019-10-13 19:59:43 BST; 1min 42s ago
  Process: 531 ExecStart=/home/pi/RPi-Jukebox-RFID/scripts/daemon_mqtt_client.py (code=exited, status=203/EXEC)
 Main PID: 531 (code=exited, status=203/EXEC)

Oct 13 19:59:42 phoniebox systemd[1]: phoniebox-mqtt-client.service: Failed with result 'exit-code'.
Oct 13 19:59:43 phoniebox systemd[1]: phoniebox-mqtt-client.service: Service hold-off time over, scheduling restart.
Oct 13 19:59:43 phoniebox systemd[1]: Stopped Phoniebox MQTT Client Service.
Oct 13 19:59:43 phoniebox systemd[1]: phoniebox-mqtt-client.service: Start request repeated too quickly.
Oct 13 19:59:43 phoniebox systemd[1]: Failed to start Phoniebox MQTT Client Service.
Oct 13 19:59:43 phoniebox systemd[1]: phoniebox-mqtt-client.service: Unit entered failed state.
Oct 13 19:59:43 phoniebox systemd[1]: phoniebox-mqtt-client.service: Failed with result 'exit-code'.```
Do you guys have any idea what the problem might be?
I already tried rebooting... but didn't work.

**Comment by whenthelight** [comment]
> Thank you guys a lot for this addon! I can't wait to realize a wake-up-alarm for my kids with it!
> I can run it and it also works if I run it manually like so: `python3 RPi-Jukebox-RFID/scripts/daemon_mqtt_client.py`.
> But when I follow the instructions on the wiki page and then run `sudo systemctl status phoniebox-mqtt-client` at the end, I always get error messages:
> 
> ```
> pi@phoniebox:~ $ sudo systemctl status phoniebox-mqtt-client
> ● phoniebox-mqtt-client.service - Phoniebox MQTT Client Service
>    Loaded: loaded (/etc/systemd/system/phoniebox-mqtt-client.service; enabled; vendor preset: enabled)
>    Active: failed (Result: exit-code) since Sun 2019-10-13 19:59:43 BST; 1min 42s ago
>   Process: 531 ExecStart=/home/pi/RPi-Jukebox-RFID/scripts/daemon_mqtt_client.py (code=exited, status=203/EXEC)
>  Main PID: 531 (code=exited, status=203/EXEC)
> 
> Oct 13 19:59:42 phoniebox systemd[1]: phoniebox-mqtt-client.service: Failed with result 'exit-code'.
> Oct 13 19:59:43 phoniebox systemd[1]: phoniebox-mqtt-client.service: Service hold-off time over, scheduling restart.
> Oct 13 19:59:43 phoniebox systemd[1]: Stopped Phoniebox MQTT Client Service.
> Oct 13 19:59:43 phoniebox systemd[1]: phoniebox-mqtt-client.service: Start request repeated too quickly.
> Oct 13 19:59:43 phoniebox systemd[1]: Failed to start Phoniebox MQTT Client Service.
> Oct 13 19:59:43 phoniebox systemd[1]: phoniebox-mqtt-client.service: Unit entered failed state.
> Oct 13 19:59:43 phoniebox systemd[1]: phoniebox-mqtt-client.service: Failed with result 'exit-code'.
> ```
> 
> Do you guys have any idea what the problem might be?
> I already tried rebooting... but didn't work.

Show was going on with : journalctl -u phoniebox-mqtt-client.service

**Comment by georgbachmann** [comment]
Sorry for the super late reply... so much stuff going on currently and so little time for the fun stuff...
The message I am getting was essentially:

    phoniebox-mqtt-client.service: Failed at step EXEC spawning /home/pi/RPi-Jukebox-RFID/scripts/daemon_mqtt_client.py: Permission denied

So I simply ran `chmod +x daemon_mqtt_client.py` any everything is now working as expected... awesome :)
Excited to see how long my kids will like "Guten morgen Sonnenschein" as their wake up sound :) haha

Again... thanks for that MQTT plugin! Love it!

**Comment by andreasbrett** [comment]
> So I simply ran `chmod +x daemon_mqtt_client.py` any everything is now working as expected

Ah I see. I had not pushed the file via git but instead pasted its contents here on github. That's why the file attributes are missing. Thanks for pointing out!

**Comment by MiczFlor** [comment]
Hi @andreasbrett can you create a pull request, please?

**Comment by andreasbrett** [comment]
> Hi @andreasbrett can you create a pull request, please?

Of course. It's done.

**Comment by s-martin** [comment]
Description for MQTT in https://github.com/MiczFlor/RPi-Jukebox-RFID/wiki/Smart-Home-remote-control-with-MQTT

Closing this issue now.
